DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog;
DROP TABLE IF EXISTS blog.user;
CREATE TABLE blog.user(
  id int AUTO_INCREMENT PRIMARY KEY  COMMENT 'id PK',
  username VARCHAR(255) NOT NULL UNIQUE COMMENT 'username',
  password VARCHAR(255) NOT NULL COMMENT 'password'
);

